# Generated by Django 4.2.26 on 2025-11-21 14:33

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliar_IMC',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=70, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=9, verbose_name='Sexo')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('escola', models.CharField(max_length=100, verbose_name='Escola')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('foto', stdimage.models.StdImageField(default='fotos/sem_foto.png', force_min_size=False, upload_to='fotos', variations={'thumb': (125, 125)}, verbose_name='Foto')),
                ('imc', models.FloatField(blank=True, null=True, verbose_name='IMC')),
            ],
        ),
    ]
