# Generated by Django 4.2.26 on 2025-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliar_imc',
            options={'verbose_name': 'Avaliação de IMC', 'verbose_name_plural': 'Avaliações de IMC'},
        ),
        migrations.AddField(
            model_name='avaliar_imc',
            name='classificacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Classificação IMC'),
        ),
        migrations.AlterField(
            model_name='avaliar_imc',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='avaliar_imc',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='avaliar_imc',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='avaliar_imc',
            name='sexo',
            field=models.CharField(choices=[('MASC', 'Masculino'), ('FEMI', 'Feminino'), ('NAOI', 'Não Informado')], max_length=9, verbose_name='Sexo'),
        ),
    ]
